export interface Article {
  slug: string;
  category: 'Phase' | 'Nutrition' | 'Movement' | 'Wellbeing' | 'Health';
  title: string;
  subtitle: string;
  emoji: string;
  readMins: number;
  accent: string; // hex
  tint: string;   // rgba bg
  sections: { heading: string; body: string }[];
}

export const ARTICLES: Article[] = [
  {
    slug: 'menstrual-phase',
    category: 'Phase',
    title: 'The Menstrual Phase',
    subtitle: 'Days 1–5 · Rest & release',
    emoji: '🌑',
    readMins: 4,
    accent: '#dc2626',
    tint: 'rgba(252,232,232,0.85)',
    sections: [
      { heading: 'What is happening', body: 'Your period marks day 1 of the cycle. Both estrogen and progesterone are at their lowest, which is why energy often dips and you may feel more inward. The uterine lining sheds, and this is a normal, healthy reset rather than something to push through.' },
      { heading: 'How you may feel', body: 'Lower energy, mild-to-moderate cramps, a need for more sleep, and a quieter mood are all typical. Some people also notice clearer thinking by days 3–4 as hormones begin a slow climb again.' },
      { heading: 'Nourish', body: 'Iron is lost with menstrual blood, so iron-rich foods (lentils, spinach, red meat, tofu) paired with vitamin C help replenish stores. Warm, cooked foods and magnesium (dark chocolate, pumpkin seeds) can ease cramping. Stay well hydrated to reduce bloating.' },
      { heading: 'Move gently', body: 'Light movement — walking, restorative yoga, gentle stretching — supports circulation and can relieve cramps without taxing a low-energy system. There is no need for intense training; honour the rest your body is asking for.' },
      { heading: 'Self-care', body: 'Heat on the lower abdomen, early nights, and lighter commitments where possible. This is a natural low point in the month — planning gentler days here pays off in the energy you regain afterward.' },
    ],
  },
  {
    slug: 'follicular-phase',
    category: 'Phase',
    title: 'The Follicular Phase',
    subtitle: 'Days 6–13 · Rise & begin',
    emoji: '🌱',
    readMins: 4,
    accent: '#7c3aed',
    tint: 'rgba(237,233,255,0.85)',
    sections: [
      { heading: 'What is happening', body: 'After your period, estrogen rises steadily as follicles in the ovary mature. This is the cycle\'s upswing: energy, mood, and mental sharpness tend to climb day by day toward ovulation.' },
      { heading: 'How you may feel', body: 'More motivated, social, and creative. Many people find this is their best window for starting projects, problem-solving, and tackling things that felt heavy the week before.' },
      { heading: 'Nourish', body: 'Rising estrogen pairs well with fresh, vibrant foods — leafy greens, sprouted grains, fermented foods, and lean protein. Lighter, raw-leaning meals often feel good now as digestion is robust.' },
      { heading: 'Move', body: 'Your body can handle and benefit from higher intensity: strength training, cardio, dance, or trying a new class. Muscles recover well and you are building toward your peak.' },
      { heading: 'Make it count', body: 'Front-load demanding work, important conversations, and new beginnings into this phase. The hormonal tailwind is real — use it.' },
    ],
  },
  {
    slug: 'ovulation-phase',
    category: 'Phase',
    title: 'The Ovulatory Phase',
    subtitle: 'Days 14–16 · Peak & connect',
    emoji: '🌕',
    readMins: 3,
    accent: '#d97706',
    tint: 'rgba(255,243,232,0.85)',
    sections: [
      { heading: 'What is happening', body: 'A surge in luteinising hormone releases an egg. Estrogen peaks and testosterone gives a brief lift, so this is typically the high point of energy, confidence, and libido in the cycle.' },
      { heading: 'How you may feel', body: 'Most outgoing, verbally fluent, and physically strong. Skin often looks its best. Some people feel a brief one-sided twinge (mittelschmerz) as the egg releases — usually harmless.' },
      { heading: 'Nourish', body: 'Support this metabolically active window with antioxidant-rich produce, fibre to help process the estrogen peak (cruciferous vegetables like broccoli), and plenty of water. Light, colourful meals suit the high energy.' },
      { heading: 'Move & connect', body: 'A great time for peak workouts, presentations, dates, and social events. If you are tracking fertility, this is the fertile window — the few days around ovulation.' },
    ],
  },
  {
    slug: 'luteal-phase',
    category: 'Phase',
    title: 'The Luteal Phase',
    subtitle: 'Days 17–28 · Wind down & nest',
    emoji: '🌘',
    readMins: 5,
    accent: '#4f46e5',
    tint: 'rgba(233,237,255,0.85)',
    sections: [
      { heading: 'What is happening', body: 'After ovulation, progesterone rises to prepare the body for a possible pregnancy. If none occurs, both progesterone and estrogen fall in the days before your period — the hormonal shift behind PMS.' },
      { heading: 'How you may feel', body: 'The early luteal phase can feel calm and steady. The late luteal phase (the few days pre-period) is when irritability, anxiety, bloating, breast tenderness, cravings, and fatigue commonly appear. This is physiology, not a personal failing.' },
      { heading: 'Nourish', body: 'Progesterone raises your metabolic rate, so genuine hunger increases — eat enough. Complex carbohydrates (oats, sweet potato, whole grains) support serotonin and steady mood. Magnesium and B6 (bananas, leafy greens, legumes) can ease PMS, and reducing salt, caffeine, and alcohol helps with bloating and sleep.' },
      { heading: 'Move', body: 'Match movement to your falling energy: strength and steady cardio early in the phase, shifting to walking, pilates, and yoga as your period approaches. Forcing high intensity late luteal often backfires.' },
      { heading: 'Self-care', body: 'Protect sleep, lower your social and work load where you can, and treat self-criticism that spikes here with extra kindness — it usually lifts the moment your period starts. Tracking symptoms across a few cycles helps you anticipate and plan for this phase.' },
    ],
  },
  {
    slug: 'understanding-pcos',
    category: 'Health',
    title: 'Understanding PCOS',
    subtitle: 'The most common hormonal disorder in women',
    emoji: '🩺',
    readMins: 6,
    accent: '#0d9488',
    tint: 'rgba(224,247,244,0.85)',
    sections: [
      { heading: 'What PCOS is', body: 'Polycystic ovary syndrome (PCOS, often called PCOD) is a hormonal and metabolic condition, not just an ovary problem. The ovaries make slightly more androgens (male-type hormones) than usual, which can interrupt the monthly release of an egg. The "cysts" in the name are actually small, undeveloped follicles — not harmful cysts — so the label is a bit misleading.' },
      { heading: 'How common is it', body: 'PCOS is the most common endocrine disorder in women of reproductive age. Global estimates range from about 6% to 20% depending on the diagnostic criteria used, with around 12% of adult women affected under the widely used Rotterdam criteria. In India, pooled studies put prevalence near 11%, with individual studies ranging from roughly 9% to 22%. In short: if it affects you, you are far from alone.' },
      { heading: 'The three signs doctors look for', body: 'Diagnosis usually follows the Rotterdam criteria — you need any 2 of these 3: (1) irregular or absent ovulation (irregular, very long, or missing periods); (2) signs of high androgens, either on a blood test or physically (acne, excess hair growth, scalp hair thinning); (3) polycystic-looking ovaries on an ultrasound. Because only 2 of 3 are needed, PCOS looks different from person to person.' },
      { heading: 'Insulin resistance: the hidden engine', body: 'Up to ~70% of women with PCOS have insulin resistance, where the body needs more insulin to manage blood sugar. High insulin pushes the ovaries to make more androgens, which worsens irregular cycles — a self-reinforcing loop. This is why PCOS is increasingly understood as a metabolic condition, and why blood-sugar-friendly habits help so much.' },
      { heading: 'Symptoms beyond periods', body: 'PCOS can show up as irregular or missing periods, acne, oily skin, excess hair on the face or body (hirsutism), thinning hair on the scalp, weight gain that is hard to shift, fatigue, and difficulty conceiving. Many people also experience mood changes. Symptoms can be mild or significant, and they can shift over time.' },
      { heading: 'Why it matters long-term', body: 'Left unmanaged, PCOS raises the risk of type 2 diabetes, high cholesterol, cardiovascular disease, and — because of infrequent periods — endometrial (uterine lining) changes. This is not meant to alarm you: it is exactly why early awareness and steady habits are so powerful. Most of these risks are strongly influenced by the same insulin-friendly lifestyle that eases day-to-day symptoms.' },
      { heading: 'The hopeful part', body: 'PCOS is highly manageable. The genetic tendency does not disappear, but symptoms, hormone levels, and cycle regularity can improve dramatically — and for many people, normalise — with the right routine. Tracking your cycle and symptoms is the first step to understanding your own pattern. The next article covers exactly how food and tracking can turn things around.' },
      { heading: 'A note', body: 'This is educational information, not a diagnosis. If you have irregular periods, unexplained weight changes, excess hair growth, or trouble conceiving, see a doctor or gynaecologist — PCOS is straightforward to evaluate with a conversation, a blood test, and sometimes an ultrasound.' },
    ],
  },
  {
    slug: 'reversing-pcos',
    category: 'Health',
    title: 'Working With PCOS: Food & Tracking',
    subtitle: 'Evidence-based ways to restore your rhythm',
    emoji: '🔄',
    readMins: 6,
    accent: '#16a34a',
    tint: 'rgba(232,248,238,0.85)',
    sections: [
      { heading: 'Can PCOS really be reversed?', body: 'Honestly: the underlying predisposition stays, so "cure" is the wrong word — but remission is very real. International guidelines name lifestyle change as the first-line treatment, ahead of medication. Many women restore regular ovulation and clear their symptoms through consistent food and movement habits. The goal is not perfection; it is a steady pattern your body can rely on.' },
      { heading: 'Why tracking is your superpower', body: 'You cannot manage what you cannot see. Logging your periods, symptoms, energy, and cravings reveals your personal pattern — how long your cycle really runs, when symptoms flare, whether changes are helping. Over a few months this turns vague frustration into clear feedback, and it gives your doctor real data instead of guesswork. For PCOS, where cycles are irregular by definition, tracking is especially valuable.' },
      { heading: 'The real lever: blood sugar', body: 'Because insulin resistance drives most PCOS, steadying blood sugar is the highest-impact change. Studies show women who improve insulin sensitivity often see symptoms ease even without much weight change — the active ingredient is insulin sensitivity, not the number on the scale. Most food advice for PCOS comes back to this one idea: avoid sharp blood-sugar spikes.' },
      { heading: 'How to eat for steadier insulin', body: 'Favour low-glycaemic, high-fibre foods (whole grains, legumes, vegetables, whole fruit over juice). Pair carbs with protein and healthy fats to blunt the sugar spike — e.g. fruit with nuts, rice with dal and vegetables. Mediterranean and anti-inflammatory patterns, plus omega-3s (fish, flax, walnuts), have the strongest evidence. Cut back on sugary drinks, refined flour, and ultra-processed snacks, which spike insulin hardest.' },
      { heading: 'A simple plate', body: 'An easy template: half the plate non-starchy vegetables, a quarter lean protein (eggs, fish, chicken, tofu, paneer, legumes), a quarter slow carbs (millets, oats, brown rice, whole-grain roti), plus a little healthy fat. Eating protein or veg before carbs in a meal further flattens the post-meal sugar rise. You do not need to be perfect — most meals trending this way is what counts.' },
      { heading: 'Movement that targets insulin', body: 'Both aerobic exercise (brisk walking, cycling, dancing) and resistance training (weights, bodyweight) improve insulin sensitivity and reproductive outcomes. Muscle is a glucose sponge, so building a little strength helps your body handle carbs. Even a 10–15 minute walk after meals measurably lowers blood-sugar spikes. Consistency beats intensity.' },
      { heading: 'The 5% rule', body: 'If weight loss is relevant for you, the evidence is encouraging: losing just 5% of body weight can boost ovulation frequency and improve hormone levels, and weight loss restores regular periods in up to ~40% of women with PCOS. Modest, sustainable change — not extreme dieting — delivers most of the benefit. And remember, the mechanism is improved insulin sensitivity, which you gain from the habits themselves.' },
      { heading: 'Consistency over perfection', body: 'PCOS responds to rhythm, not heroics. Pick one or two changes — a post-meal walk, protein at breakfast, swapping sugary drinks — and let them become automatic before adding more. Track as you go so you can see what works for your body. Combined with your doctor\'s guidance, these steady habits are how many people quietly turn PCOS around.' },
    ],
  },
  {
    slug: 'cycle-syncing-basics',
    category: 'Wellbeing',
    title: 'Cycle Syncing, Simply',
    subtitle: 'Living with your rhythm, not against it',
    emoji: '🔄',
    readMins: 3,
    accent: '#6E3482',
    tint: 'rgba(245,235,250,0.9)',
    sections: [
      { heading: 'The idea', body: 'Your hormones follow a roughly monthly rhythm, and so do your energy, mood, and recovery. Cycle syncing means loosely matching your food, movement, and workload to the phase you are in — leaning into the high-energy follicular and ovulatory weeks, and easing off during menstruation and the late luteal phase.' },
      { heading: 'Why track', body: 'Everyone\'s cycle is individual. A few months of logging reveals your personal patterns — when energy reliably dips, when cravings hit, how long your cycle truly runs — which makes predictions and recommendations genuinely yours rather than textbook averages.' },
      { heading: 'Start small', body: 'You do not need to overhaul your life. Pick one lever — maybe scheduling demanding work for your follicular phase, or planning gentler days before your period — and build from there. Bloom learns alongside you.' },
    ],
  },
  {
    slug: 'fertility-awareness',
    category: 'Health',
    title: 'Fertility Awareness & TTC',
    subtitle: 'Reading your fertile window with mucus & temperature',
    emoji: '🌡️',
    readMins: 6,
    accent: '#0891b2',
    tint: 'rgba(224,247,250,0.85)',
    sections: [
      { heading: 'Your fertile window', body: 'You can only conceive on a handful of days each cycle. The egg lives about 12–24 hours after ovulation, but sperm can survive up to 5 days inside the body — so the fertile window is roughly the 5 days before ovulation plus the day of ovulation itself. Identifying those days is the heart of fertility awareness.' },
      { heading: 'The cervical mucus method', body: 'Cervical mucus changes predictably across the cycle: dry just after your period, then sticky, creamy, and finally clear, stretchy, and slippery — like raw egg white — in the day or two before ovulation. That egg-white mucus is the most fertile sign and means ovulation is near. Watery and egg-white days are your green light.' },
      { heading: 'Basal body temperature (BBT)', body: 'After ovulation, progesterone nudges your resting body temperature up by about 0.3°C. A sustained rise confirms ovulation has already happened. Take your temperature first thing every morning, before getting up, with a sensitive thermometer — the pattern, not any single reading, is what matters.' },
      { heading: 'Why combine both (the symptothermal method)', body: 'Mucus looks ahead — it warns you ovulation is coming. BBT looks back — it confirms ovulation occurred. Used together they pin down your fertile window far more accurately than either alone, and more accurately than a calendar guess. This is why Bloom lets you log both.' },
      { heading: 'Logging in Bloom', body: 'Adding cervical mucus and morning BBT to your daily log sharpens your predictions over time and helps confirm your personal ovulation day rather than a textbook average. These signals are entirely optional — your core predictions work from period dates alone — but they reward the effort if you are trying to conceive.' },
      { heading: 'Trying to conceive vs avoiding', body: 'To conceive, aim for intercourse on your fertile and egg-white-mucus days, especially the 2–3 days before ovulation. To avoid pregnancy, fertility awareness can work but requires careful training and consistency, and it is less reliable than medical contraception — speak to a provider before relying on it.' },
      { heading: 'A note', body: 'This is educational, not medical advice. If you have been trying to conceive for over a year (or six months if you are 35+), or your cycles are very irregular, see a doctor — many causes are treatable, and earlier evaluation helps.' },
    ],
  },
  {
    slug: 'pms-and-pmdd',
    category: 'Wellbeing',
    title: 'PMS & PMDD',
    subtitle: 'When the luteal phase hits hard',
    emoji: '🌧️',
    readMins: 5,
    accent: '#db2777',
    tint: 'rgba(252,231,243,0.85)',
    sections: [
      { heading: 'What PMS is', body: 'Premenstrual syndrome is the cluster of physical and emotional symptoms that appear in the luteal phase — the week or so before your period — and fade once bleeding starts. It is driven by the natural drop in estrogen and progesterone, not by anything you did. Common signs include bloating, breast tenderness, cramps, fatigue, irritability, low mood, and food cravings.' },
      { heading: 'The spectrum', body: 'PMS ranges from barely noticeable to genuinely disruptive. Most people who menstruate experience some premenstrual symptoms; for a minority they are severe enough to interfere with work, relationships, or daily life. Severity can also change across your life and from cycle to cycle.' },
      { heading: 'PMDD: the severe end', body: 'Premenstrual dysphoric disorder (PMDD) affects roughly 3–8% of menstruating people. It is marked by intense mood symptoms — depression, anxiety, anger, or feeling out of control — that seriously affect daily functioning and lift within a few days of the period starting. PMDD is a recognised medical condition and very treatable; it is not a character flaw or simply "bad PMS."' },
      { heading: 'Tracking is how it is diagnosed', body: 'The defining feature of PMS and PMDD is timing: symptoms cluster in the luteal phase and disappear in the follicular phase. Logging your mood and symptoms across at least two cycles reveals that pattern clearly, which is exactly what a clinician needs to distinguish PMDD from a year-round mood condition. Your Bloom logs make that conversation far more productive.' },
      { heading: 'What helps day to day', body: 'Regular aerobic exercise, steady sleep, and complex carbohydrates support mood. Reducing caffeine, alcohol, and salt eases irritability, sleep, and bloating. Calcium, magnesium, and vitamin B6 have modest evidence for symptom relief. Planning a lighter schedule for your late luteal days, where possible, also makes a real difference.' },
      { heading: 'When to seek help', body: 'If premenstrual symptoms regularly disrupt your life, relationships, or work — or if you experience low mood, hopelessness, or thoughts of self-harm — please talk to a doctor. Effective treatments exist, including certain antidepressants, hormonal options, and cognitive approaches. You do not have to just endure it.' },
    ],
  },
  {
    slug: 'when-to-see-a-doctor',
    category: 'Health',
    title: 'When to See a Doctor',
    subtitle: 'Period red flags worth checking',
    emoji: '🚩',
    readMins: 5,
    accent: '#be123c',
    tint: 'rgba(255,228,230,0.85)',
    sections: [
      { heading: 'Why this matters', body: 'Periods vary a lot between people, and most variation is completely normal. But a few patterns are worth getting checked — not to alarm you, but because many causes are simple to treat when caught early. Tracking your cycle makes these changes easier to spot and easier to describe to a clinician.' },
      { heading: 'Very heavy bleeding', body: 'See a doctor if you soak through a pad or tampon every hour for several hours, pass clots larger than a coin, bleed through to clothing or bedding regularly, or need double protection. Heavy menstrual bleeding can cause anaemia and often has a manageable cause.' },
      { heading: 'Severe or worsening pain', body: 'Period cramps are common, but pain that stops you doing normal activities, does not ease with usual pain relief, or steadily worsens over time deserves evaluation — it can be a sign of conditions like endometriosis or fibroids, which benefit from earlier diagnosis.' },
      { heading: 'Bleeding at unexpected times', body: 'Bleeding between periods, after sex, or any bleeding after menopause should always be checked. It is often harmless, but it is one of the clearest signals to get a professional opinion rather than wait.' },
      { heading: 'Cycles that are very irregular or have changed', body: 'Worth a conversation: periods that suddenly stop for several months (and you are not pregnant), cycles consistently shorter than 21 days or longer than 35 days, periods lasting more than 7 days, or a marked change from your own normal pattern. Irregularity can point to thyroid issues, PCOS, stress, or perimenopause.' },
      { heading: 'Seek urgent care', body: 'Get prompt medical attention for fever with pelvic pain, fainting or severe dizziness from blood loss, sudden severe abdominal pain, or any bleeding or pain during a known or possible pregnancy. When in doubt, it is always reasonable to ask.' },
      { heading: 'Trust yourself', body: 'You know your body best. If something feels off — even if it is not on this list — that instinct is a valid reason to see a doctor. This article is educational and does not replace a personal medical assessment.' },
    ],
  },
  {
    slug: 'contraception-and-your-cycle',
    category: 'Health',
    title: 'Contraception & Your Cycle',
    subtitle: 'How birth control changes what you track',
    emoji: '💊',
    readMins: 5,
    accent: '#2563eb',
    tint: 'rgba(230,238,255,0.85)',
    sections: [
      { heading: 'Two broad types', body: 'Contraception falls into hormonal methods (the pill, patch, ring, implant, hormonal IUD, and injection) and non-hormonal methods (copper IUD, condoms, diaphragms, and fertility awareness). They affect your natural cycle — and therefore what tracking shows — in very different ways.' },
      { heading: 'On hormonal methods', body: 'Most hormonal contraceptives work mainly by preventing ovulation. Because there is no true ovulation, there is no natural cycle to predict. The bleed you may get on the combined pill during the placebo week is a "withdrawal bleed," not a real period — it is a response to stopping hormones, not the end of an ovulatory cycle.' },
      { heading: 'What tracking is good for here', body: 'With no ovulation to forecast, cycle predictions are less meaningful — but logging is still valuable. Tracking symptoms, mood, bleeding, and side effects helps you and your provider see how a method suits you, especially in the first few months or after a switch.' },
      { heading: 'On non-hormonal methods', body: 'The copper IUD, condoms, and fertility awareness do not suppress ovulation, so your natural cycle continues and predictions stay useful. The copper IUD can make periods heavier or crampier, particularly early on — tracking helps you tell a settling-in phase from a pattern worth discussing.' },
      { heading: 'Starting or stopping', body: 'When you stop hormonal contraception, it can take a few cycles for your natural rhythm to return and become predictable again — this is normal. Logging from the moment you stop helps Bloom (and you) learn your re-emerging pattern faster.' },
      { heading: 'A note', body: 'The right method is a personal decision that balances effectiveness, side effects, health history, and your goals. This is general information — talk to a doctor or family-planning clinic to choose and review what fits you.' },
    ],
  },
  {
    slug: 'perimenopause-basics',
    category: 'Health',
    title: 'Perimenopause Basics',
    subtitle: 'The transition before menopause',
    emoji: '🌗',
    readMins: 5,
    accent: '#a16207',
    tint: 'rgba(254,249,231,0.85)',
    sections: [
      { heading: 'What perimenopause is', body: 'Perimenopause is the transition leading up to menopause, when the ovaries gradually wind down. It commonly begins in the 40s — though it can start in the mid-30s — and typically lasts around 4 to 8 years. It ends at menopause, defined as 12 consecutive months with no period.' },
      { heading: 'The hormonal shift', body: 'Rather than a smooth decline, estrogen tends to fluctuate unpredictably during perimenopause before falling overall, while ovulation becomes less regular. These swings — not just lower hormones — are behind many of the symptoms, which is why this phase can feel like a moving target.' },
      { heading: 'How your cycle changes', body: 'Cycles often become less predictable: lengths vary, periods may be skipped, and flow can become heavier or lighter than your norm. This irregularity is an expected part of the transition. Tracking it gives you a clear record of how your own pattern is shifting.' },
      { heading: 'Common symptoms', body: 'Alongside changing periods, you may notice hot flushes, night sweats, disturbed sleep, mood changes or irritability, brain fog, lower libido, and vaginal dryness. Symptoms vary enormously between people — some sail through, others find them disruptive.' },
      { heading: 'Why tracking helps', body: 'Logging your cycles and symptoms helps you recognise that scattered changes belong to one transition, and it gives your doctor concrete information. A symptom and bleeding record is especially useful for flagging anything that needs a closer look, like unusually heavy or unexpected bleeding.' },
      { heading: 'Support is available', body: 'Perimenopause is a natural stage, not something you must simply tolerate. Lifestyle measures, and where appropriate menopausal hormone therapy or other treatments, can ease symptoms significantly. If symptoms affect your quality of life, a doctor can help — this article is educational and not a substitute for that conversation.' },
    ],
  },
  {
    slug: 'eating-with-your-cycle',
    category: 'Nutrition',
    title: 'Eating With Your Cycle',
    subtitle: 'A phase-by-phase nutrition guide',
    emoji: '🥗',
    readMins: 5,
    accent: '#15803d',
    tint: 'rgba(232,248,238,0.85)',
    sections: [
      { heading: 'The principle', body: 'Your nutritional needs shift a little across the month as hormones rise and fall. You do not need a rigid diet — just gentle adjustments that support how your body is working in each phase. Whole, minimally processed foods and steady hydration are the foundation all month long.' },
      { heading: 'Menstrual phase', body: 'You lose iron with menstrual blood, so iron-rich foods (lentils, spinach, tofu, red meat) paired with vitamin C aid absorption. Warm, cooked, comforting meals and magnesium-rich foods (dark chocolate, pumpkin seeds) can ease cramps, while good hydration reduces bloating. This is a phase to nourish, not restrict.' },
      { heading: 'Follicular phase', body: 'As estrogen rises and energy climbs, lighter, fresh, vibrant foods tend to feel good — leafy greens, sprouted grains, fermented foods, and lean protein to support the body building toward ovulation. Digestion is usually robust now, so raw-leaning meals sit well.' },
      { heading: 'Ovulatory phase', body: 'Around your energy peak, lean on antioxidant-rich produce and fibre to help your body process the estrogen high — cruciferous vegetables like broccoli, cauliflower, and cabbage are especially helpful. Colourful, lighter meals and plenty of water suit this active window.' },
      { heading: 'Luteal phase', body: 'Rising progesterone increases your metabolic rate and genuine hunger — so eat enough. Complex carbohydrates (oats, sweet potato, whole grains) support serotonin and steady mood, and magnesium and B6 (bananas, legumes, leafy greens) can ease PMS. Easing off salt, caffeine, and alcohol helps with bloating and sleep, and choosing slow carbs over sugar tames cravings.' },
      { heading: 'All month', body: 'Across every phase: prioritise protein, fibre, and healthy fats, stay hydrated, and avoid under-eating. The goal is steady energy and steady blood sugar, not perfection. Log how foods and cravings track with your cycle to learn what genuinely works for your body.' },
      { heading: 'A note', body: 'This is general nutrition guidance, not personalised medical or dietary advice. If you have a health condition such as PCOS, diabetes, or an eating disorder history, check with a doctor or dietitian before making changes.' },
    ],
  },
];

export function getArticle(slug: string) {
  return ARTICLES.find((a) => a.slug === slug);
}
